# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 20:41
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='post_imgs'),
        ),
    ]
