# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-30 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180904_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1500),
        ),
    ]
